### ISSUE TITLE
colorrange attribute is being ignored in visual()

### ISSUE THREAD

**Issue by flyaflya** [JuliaPlots/AlgebraOfGraphics.jl#281] opened 2021-09-23 18:09 UTC
See the below picture:

![image](https://user-images.githubusercontent.com/17184441/134560490-94b2b4ca-14cd-46cc-99c1-92846f596802.png)

I believe the points on the left and the points on the right should all be the exact same color, but they are not.  I think I implemented this correctly.  Here is the code to reproduce the bug:

```
using CairoMakie, AlgebraOfGraphics

x = randn(100)
y = randn(100)
z = x .* y

## Aog Plot
plt = data((x = x, y = y, z = z)) * mapping(:x,:y,color = :z) * visual(markersize = 12, colormap = :viridis, colorrange = (-5,5))
aogGrid = draw(plt, axis = (title = "AOG",))

## Makie Plot
fig, = scatter(x,y, color = z, markersize = 12, colormap = :viridis, colorrange = (-5,5),axis = (title = "MAKIE",))
Colorbar(fig[1, 2], colormap = :viridis, colorrange = (-5,5))
fig

draw!(fig[1,3],plt, axis = (title = "AOG",))
colorbar!(fig[1,4],aogGrid)
current_figure()
```

**Comment by SimonDanisch** [comment] 2021-09-28 08:47
Duplicate of: https://github.com/JuliaPlots/AlgebraOfGraphics.jl/issues/223

**Closed by SimonDanisch** 2021-09-28 08:47 UTC
