### ISSUE TITLE
Limit data range on y-axis (violin plot/box plot)

### ISSUE THREAD

**Issue by roland-KA** [JuliaPlots/AlgebraOfGraphics.jl#263] opened 2021-08-17 14:09 UTC
I have created a box plot (and a similar violin plot) using AoG and would like to restrict the data shown on the y-axis (see: https://github.com/roland-KA/StatisticalPlotsWithJulia, the violin plot and the box plot are in the Pluto notebook `notebooks/DV-Basics-AlgebraOfGraphics.jl` in section "*Box Plots and Violin Plots*"). The maximum y-value is 200,000 and would like to restrict that to 100,000.

Up to now I've tried using
- `ylims` (on the axis)
- `datalimits` (within the `visual` function)

but neither of these attempts had any effect. So how can I do that?

**Comment by piever** [comment] 2021-08-19 11:52
Do you have a simple copy-pastable MWE? I think `datalimits` (passing either a tuple of values of a function of the data should work):

```julia
julia> using AlgebraOfGraphics, CairoMakie

julia> df = (x=rand(["a", "b"], 10), y=rand(10));

julia> plt = data(df) * mapping(:x, :y) * visual(Violin, datalimits=(-Inf, 0.5));

julia> draw(plt)
```

**Comment by roland-KA** [comment] 2021-08-22 14:17
I've stripped down the code now to the basics as follows (there is also a Pluto notebook named `AoG-Datalimits.jl` at [https://github.com/roland-KA/StatisticalPlotsWithJulia/tree/main/notebooks]() with that code):

```
using AlgebraOfGraphics
using GLMakie
using DataFrames
using CSV
using HTTP

# fetch and prepare data
countries = CSV.File(HTTP.get("https://raw.githubusercontent.com/roland-KA/StatisticalPlotsWithJulia/main/data/countries.csv").body) |> DataFrame
dropmissing!(countries)
countries.GDPperCapita = countries.GDP ./ countries.Pop2019

# box plot
boxGDPperCapita = 
	data(countries) * 
	visual(BoxPlot, show_notch = true, datalimits = (-Inf, 100000)) *
	mapping(:Region, :GDPperCapita, color = :Region) 
draw(boxGDPperCapita)

# violin plot
violinGDPperCapita = 
	data(countries) * 
	visual(Violin, show_notch = true, datalimits = (-Inf, 100000)) *
	mapping(:Region, :GDPperCapita, color = :Region) 
draw(violinGDPperCapita)
```

The interesting thing is: `datalimits` works as intended with the violin plot, but it has no effect on the box plot.

**Comment by piever** [comment] 2022-02-24 16:41
Closing here as I think this is the intended behavior. `Makie.boxplot` does not support `datalimits`. I confess I'm not sure what it would mean for a `boxplot` to have data limits, but the implementation would need to happen in Makie.

**Closed by piever** 2022-02-24 16:41 UTC

**Comment by roland-KA** [comment] 2022-02-24 17:40
The intended behavior was to show only that part of the boxplot within the limits of `datalimits` (sort of a zoom-in). That doesn't work for a **boxplot**.

This is strange, since `datalimits` works this way on **violinplots**. As violinplots and boxplots serve quite similar purposes, this inconsistent behavior doesn't make sense in my opinion.
