### ISSUE TITLE
Very slow plotting of pair() type plot compared to R

### ISSUE THREAD

**Issue by Denis-Titov** [JuliaPlots/AlgebraOfGraphics.jl#315] opened 2021-12-24 09:30 UTC
I'm trying to follow Introduction to Statistical Learning book tutorials using Julia and R.

For one of the plots, AlgebraOfGraphics take 15 sec to plot this every time (so not a TTFP issue) while R is "instantaneous".
Not sure what the issue is but seems like something in AoG is taking a very long time so I thought it might be worth reporting this or maybe I'm doing something wrong using AoG.

Plot uses the following code (`Auto` dataset can be found here(https://www.statlearning.com/resources-second-edition)):

```
using DataFrames, CairoMakie, AlgebraOfGraphics, CSV

Auto = CSV.read("ALL CSV FILES - 2nd Edition/Auto.csv", DataFrame, missingstring = "?")
Auto = dropmissing(Auto)
cols_to_plot = [:mpg, :displacement, :horsepower, :weight, :acceleration]
#plt = data(Auto) * visual(BoxPlot) * mapping(:cylinders, :mpg)
plt =
    data(Auto) *
    visual(Scatter) *
    mapping(reshape(cols_to_plot, 1, length(cols_to_plot)), cols_to_plot, row = dims(1), col = dims(2))
@time draw(plt, figure = (resolution = (1500, 1500),))
```

It takes about 15 sec to plot this on my system while R code is instantaneous:
```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 6
```

R code is here:
```
> install.packages("ISLR2")
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.1/ISLR2_1.3.tgz'
Content type 'application/x-gzip' length 4162248 bytes (4.0 MB)
==================================================
downloaded 4.0 MB


The downloaded binary packages are in
	/var/folders/zg/hbt8knld6mx_jvnq21hbjdwh0000gn/T//RtmpEy34ZG/downloaded_packages
> library(ISLR2)

Attaching package: ‘ISLR2’

The following object is masked _by_ ‘.GlobalEnv’:

    College

> pairs(~ mpg + displacement +horsepower + weight +acceleration, data=Auto)
```

Edit: StatsPlots is also pretty fast 0.06sec
Code:
```
using StatsPlots
@time @df Auto corrplot([:mpg :displacement :horsepower :weight :acceleration], grid = false)
```

**Comment by piever** [comment] 2021-12-30 11:56
There seems to be a performance bug in Makie with the creation of multiple axes.

Doing things manually with Makie also is surprisingly slow:

```julia
julia> using CairoMakie

julia> @time begin
           f = Figure()
           axs = [Axis(f[i, j]) for i in 1:5 for j in 1:5]

           for ax in axs
               scatter!(ax, rand(100), rand(100))
           end

           linkxaxes!(axs...)
           linkyaxes!(axs...)
           foreach(hidexdecorations!, axs)
           foreach(hideydecorations!, axs)
       end
  9.040071 seconds (137.32 M allocations: 2.602 GiB, 7.14% gc time, 1.05% compilation time)
```

It's definitely important to measure (and reduce, if it is non-negligible) the overhead from using AlgebraOfGraphics, but we should also fix the performance of multiple subplots in Makie.

@jkrumbiegel Have you noticed this performance issue as well? Is it something that can be fixed via https://github.com/JuliaPlots/Makie.jl/pull/1355?

**Comment by jkrumbiegel** [comment] 2021-12-30 22:41
The problem is that all objects are connected with each other in the observable-bound layout, so any time one of them changes a parameter that influences the layout, all of them update. Which is a big waste of computation obviously.

A large chunk of it can be avoided like this:

```julia
@time begin
    f = Figure()
    f.layout.block_updates = true
    axs = [Axis(f[i, j]) for i in 1:5 for j in 1:5]

    for ax in axs
        scatter!(ax, rand(100), rand(100))
    end

    linkaxes!(axs...)
    foreach(hidedecorations!, axs)
    f.layout.block_updates = false
    Makie.GridLayoutBase.update!(f.layout)
end
```

But probably there can be done more to reduce unnecessary updates in the Axis itself.

**Comment by piever** [comment] 2022-01-03 18:16
Thanks for the tip! I've been playing with the `f.layout.block_updates = true` trick here and it does speed up things substantially (the above example went from 15 seconds to 1 second). Can the field `block_updates` be considered part of the public API? Otherwise, I was thinking one could add something like the following to Makie, as a public API:

```julia
function update(f, fig)
    layout = fig.layout
    block_updates = layout.block_updates
    layout.block_updates = true
    output = f(fig)
    layout.block_updates = block_updates
    block_updates || Makie.GridLayoutBase.update!(layout)
    return output
end
```

So that one can do all layout updates in a `do ... end` block efficiently.

**Comment by piever** [comment] 2022-02-07 09:43
The above strategy is now implemented on master (time for the pair plot in the OP is now around 1s). I'm closing here as I don't think there's anything else actionable on the AlgebraOfGraphics side.

**Closed by piever** 2022-02-07 09:43 UTC
